# Generated by Django 4.2.19 on 2025-03-17 08:39

from django.db import migrations
import djangocms_link.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spouse',
            name='link',
            field=djangocms_link.fields.LinkField(default=dict, help_text='-'),
        ),
    ]
