# Generated by Django 3.2 on 2021-09-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('total_amount', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('0', 'unpaid'), ('1', 'paid'), ('2', 'done'), ('-1', 'cancelled')], max_length=2)),
            ],
        ),
    ]
