# Generated by Django 4.2 on 2025-10-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0042_remove_placeholderreference_placeholder_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GistPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('gist_id', models.CharField(default='', help_text='Supply ID of Gist', max_length=32, verbose_name='Gist ID')),
                ('gist_user', models.CharField(default='', help_text='Supply username of Github user', max_length=32, verbose_name='Github User')),
                ('gist_filename', models.CharField(blank=True, default='', help_text='Optional. Supply a filename', max_length=250, verbose_name='Gist Filename')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
